package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name="alumno"
    ,schema="public"
)
public class Alumno  implements java.io.Serializable {


     private int id;
     private String apellido;
     private String nombre;
     private Date fechanac;
     private Integer edad;
     private String apellidorepresentante;
     private String nombrerepresentante;
     private String relacion;
     private String telefono;
     private Set matriculas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int id) {
        this.id = id;
    }
    public Alumno(int id, String apellido, String nombre, Date fechanac, Integer edad, String apellidorepresentante, String nombrerepresentante, String relacion, String telefono, Set matriculas) {
       this.id = id;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechanac = fechanac;
       this.edad = edad;
       this.apellidorepresentante = apellidorepresentante;
       this.nombrerepresentante = nombrerepresentante;
       this.relacion = relacion;
       this.telefono = telefono;
       this.matriculas = matriculas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="apellido", length=25)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="nombre", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechanac", length=13)
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }

    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    
    @Column(name="apellidorepresentante", length=25)
    public String getApellidorepresentante() {
        return this.apellidorepresentante;
    }
    
    public void setApellidorepresentante(String apellidorepresentante) {
        this.apellidorepresentante = apellidorepresentante;
    }

    
    @Column(name="nombrerepresentante", length=25)
    public String getNombrerepresentante() {
        return this.nombrerepresentante;
    }
    
    public void setNombrerepresentante(String nombrerepresentante) {
        this.nombrerepresentante = nombrerepresentante;
    }

    
    @Column(name="relacion", length=25)
    public String getRelacion() {
        return this.relacion;
    }
    
    public void setRelacion(String relacion) {
        this.relacion = relacion;
    }

    
    @Column(name="telefono", length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alumno")
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


