package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Matricula generated by hbm2java
 */
@Entity
@Table(name="matricula"
    ,schema="public"
)
public class Matricula  implements java.io.Serializable {


     private int id;
     private Alumno alumno;
     private Categoria categoria;
     private Curso curso;
     private Date fecha;
     private BigDecimal valormatricula;
     private BigDecimal valormensualidad;
     private BigDecimal nummeses;
     private Character estado;
     private Set pagos = new HashSet(0);
     private Set ventas = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(int id, Alumno alumno, Categoria categoria, Curso curso) {
        this.id = id;
        this.alumno = alumno;
        this.categoria = categoria;
        this.curso = curso;
    }
    public Matricula(int id, Alumno alumno, Categoria categoria, Curso curso, Date fecha, BigDecimal valormatricula, BigDecimal valormensualidad, BigDecimal nummeses, Character estado, Set pagos, Set ventas) {
       this.id = id;
       this.alumno = alumno;
       this.categoria = categoria;
       this.curso = curso;
       this.fecha = fecha;
       this.valormatricula = valormatricula;
       this.valormensualidad = valormensualidad;
       this.nummeses = nummeses;
       this.estado = estado;
       this.pagos = pagos;
       this.ventas = ventas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idalumno", nullable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="valormatricula", precision=4)
    public BigDecimal getValormatricula() {
        return this.valormatricula;
    }
    
    public void setValormatricula(BigDecimal valormatricula) {
        this.valormatricula = valormatricula;
    }

    
    @Column(name="valormensualidad", precision=4)
    public BigDecimal getValormensualidad() {
        return this.valormensualidad;
    }
    
    public void setValormensualidad(BigDecimal valormensualidad) {
        this.valormensualidad = valormensualidad;
    }

    
    @Column(name="nummeses", precision=3, scale=1)
    public BigDecimal getNummeses() {
        return this.nummeses;
    }
    
    public void setNummeses(BigDecimal nummeses) {
        this.nummeses = nummeses;
    }

    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matricula")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matricula")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


