package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagoventa generated by hbm2java
 */
@Entity
@Table(name="pagoventa"
    ,schema="public"
)
public class Pagoventa  implements java.io.Serializable {


     private int id;
     private Venta venta;
     private BigDecimal valor;
     private Date fecha;
     private Integer numrecibo;
     private Character estado;

    public Pagoventa() {
    }

	
    public Pagoventa(int id, Venta venta) {
        this.id = id;
        this.venta = venta;
    }
    public Pagoventa(int id, Venta venta, BigDecimal valor, Date fecha, Integer numrecibo, Character estado) {
       this.id = id;
       this.venta = venta;
       this.valor = valor;
       this.fecha = fecha;
       this.numrecibo = numrecibo;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idventa", nullable=false)
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    
    @Column(name="valor", precision=5)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="numrecibo")
    public Integer getNumrecibo() {
        return this.numrecibo;
    }
    
    public void setNumrecibo(Integer numrecibo) {
        this.numrecibo = numrecibo;
    }

    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


