package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Precio generated by hbm2java
 */
@Entity
@Table(name="precio"
    ,schema="public"
)
public class Precio  implements java.io.Serializable {


     private int id;
     private BigDecimal valor;
     private Date fechainicio;
     private Date fechafin;
     private Character estado;

    public Precio() {
    }

	
    public Precio(int id) {
        this.id = id;
    }
    public Precio(int id, BigDecimal valor, Date fechainicio, Date fechafin, Character estado) {
       this.id = id;
       this.valor = valor;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="valor", precision=5)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechainicio", length=13)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechafin", length=13)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


