package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocurso generated by hbm2java
 */
@Entity
@Table(name="tipocurso"
    ,schema="public"
)
public class Tipocurso  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Character estado;
     private Set cursos = new HashSet(0);

    public Tipocurso() {
    }

	
    public Tipocurso(int id) {
        this.id = id;
    }
    public Tipocurso(int id, String descripcion, Character estado, Set cursos) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.cursos = cursos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=25)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipocurso")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


