package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int id;
     private String usuario;
     private String clave;
     private String tipousuario;

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, String usuario, String clave, String tipousuario) {
       this.id = id;
       this.usuario = usuario;
       this.clave = clave;
       this.tipousuario = tipousuario;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="usuario", length=25)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="clave")
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="tipousuario")
    public String getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }




}


