package Pojos;
// Generated 29-jun-2017 18:26:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
    ,schema="public"
)
public class Venta  implements java.io.Serializable {


     private int id;
     private Matricula matricula;
     private Producto producto;
     private Date fecha;
     private Character estado;
     private Set pagoventas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int id, Matricula matricula, Producto producto) {
        this.id = id;
        this.matricula = matricula;
        this.producto = producto;
    }
    public Venta(int id, Matricula matricula, Producto producto, Date fecha, Character estado, Set pagoventas) {
       this.id = id;
       this.matricula = matricula;
       this.producto = producto;
       this.fecha = fecha;
       this.estado = estado;
       this.pagoventas = pagoventas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmatricula", nullable=false)
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproducto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="venta")
    public Set getPagoventas() {
        return this.pagoventas;
    }
    
    public void setPagoventas(Set pagoventas) {
        this.pagoventas = pagoventas;
    }




}


